### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rtybanana** [caughtinflux/Apex#2]
Springboard crash when attempting to enter edit mode on any nested app

**Comment by caughtinflux** [comment]
Duplicate of #1

**Comment by caughtinflux** [comment]
Or maybe not? What are the steps to reproduce this crash?

**Comment by rtybanana** [comment]
Open any group and tap and hold a nested app, close the group and reopen a different group. Crashes the springboard on the latest hotfix

**Comment by caughtinflux** [comment]
@rtybanana please check if the issue still occurs on the latest build

**Comment by rtybanana** [comment]
Issue is fixed in the latest build.

rtybanana

**Comment by caughtinflux** [comment]
Sweet, thanks!
