### ISSUE TITLE
Folder disappears when moving apps

### ISSUE THREAD

**Issue by ghost** [caughtinflux/Apex#4]
Came across this extremely weird issue once installing the latest beta of Apex 2. 

iPhone 6S 9.3.2

On the homescreen if you put a folder on the last row from the top and put in at the far right and move an icon from a different page, the folder will disappear until you're out of moving apps. I was able to reproduce this issue with every folder. It doesn't seem to happen if the app is from the same page.

**Comment by caughtinflux** [comment]
I can't really reproduce the issue based on that explanation. Would you care to elaborate, or better yet, show me a video of it in action?

**Comment by ghost** [comment]
Yea no problem! Here is the screen recording of the issue.

https://www.dropbox.com/s/v6cl1dazvtp5pbc/0F8B0DDA-4B1A-446E-BF36-0044E43B0A6B.mov?dl=0

**Comment by caughtinflux** [comment]
Pretty sure that's stock behaviour, the last icon is push to the next page if the page you're dragging an icon into is full. Can you verify by uninstalling Apex and trying the same again?

**Comment by ghost** [comment]
Wow, sorry for the trouble! I assumed it was an issue with Apex since the folder disappeared completely until you let go of an app. I uninstalled Apex and the issue repeated.

Regardless Apex works perfectly!
