### ISSUE TITLE
Icon shows grabber on top and bottom when one app is active

### ISSUE THREAD

**Issue by ghost** [caughtinflux/Apex#5]
iPhone 6S 9.3.1

If you enable grabber in settings and create a new Apex, it will show a grabber on both top and bottom if ony one app is active. I've created one with three apps on the top, bottom, and the side but only the top and bottom have a grabber, and not the side.

**Comment by caughtinflux** [comment]
This is intended behaviour, Apex does not show grabbers on the sides, and also displays both grabbers for any apps that have grouped icons.

**Comment by raydelvalle** [comment]
I can also report the same little  Visual tweak when enabling grabbers in the largest Apex update. When enable and you choose a app to be placed behind anther while this optinon is choosing. It will display two grabbers one on top as will as one on bottem.

**Comment by raydelvalle** [comment]
Sorry for got to add in last comment this issue (while not bad) is on iPhone 6s Plus running jailbreak on iOS 9.3.3

**Comment by caughtinflux** [comment]
Like I said, this is intended behaviour.
